"use client"
import Link from "next/link"
import { CrmDetailPagination } from "./crm-detail-pagination"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { CalendarDays, ChevronLeft, ChevronRight, MessageCircle, Send, StickyNote, Users } from "lucide-react"
import { addInquiryNoteAction, recordInquiryContactAction, transitionInquiryAction } from "@/app/panel/solicitudes/actions"
import { customerWhatsAppUrl, templateLabels, whatsappMessage, type WhatsAppTemplate } from "@/lib/admin-crm/whatsapp"
import { activeInquiryStatuses, inquiryStatusLabels, type CrmInquiry, type InquiryStatus, type PagedResult, type PublishedCabinOption } from "@/lib/admin-crm/types"

const field="min-h-11 w-full rounded-lg border border-border bg-background px-3 text-sm"; const button="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-border px-3 text-sm font-medium hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"
const businessStatuses: InquiryStatus[]=["new","contacted","pending","confirmed","unavailable","no_response","cancelled","completed"]
const eventLabel: Record<string,string>={received:"Solicitud recibida",whatsapp_opened:"WhatsApp abierto",status_changed:"Estado actualizado",note_added:"Nota agregada",alternative_offered:"Alternativa preparada"}
const dateTime=(value:string|null)=>value?new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Monterrey"}).format(new Date(value)):"Sin registro"
function href(params:Record<string,string|undefined>, patch:Record<string,string|number|undefined>){const next=new URLSearchParams();for(const [key,value] of Object.entries({...params,...patch}))if(value!==undefined&&value!=="")next.set(key,String(value));return `?${next}`}

export function RequestsWorkspace({page,selected,cabins,params}:{page:PagedResult<CrmInquiry>;selected:CrmInquiry|null;cabins:PublishedCabinOption[];params:Record<string,string|undefined>}){
 const router=useRouter();const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");const [note,setNote]=useState("");const [draft,setDraft]=useState<{selectedId:string|null;template:WhatsAppTemplate;alternativeId:string;message:string}>({selectedId:selected?.id??null,template:"received",alternativeId:"",message:selected?whatsappMessage("received",selected):""});
 const [optimistic,setOptimistic]=useState<{id:string;status:InquiryStatus;version:number}|null>(selected?{id:selected.id,status:selected.status,version:selected.version}:null);
 const currentOptimistic=optimistic&&selected&&optimistic.id===selected.id&&optimistic.version>selected.version?optimistic:null;
 const activeDraft=draft.selectedId===selected?.id?draft:{selectedId:selected?.id??null,template:"received" as WhatsAppTemplate,alternativeId:"",message:selected?whatsappMessage("received",selected):""};const alternative=cabins.find(c=>c.id===activeDraft.alternativeId);
 const regenerate=(value:WhatsAppTemplate,alt=alternative)=>{if(selected)setDraft({selectedId:selected.id,template:value,alternativeId:alt?.id??"",message:whatsappMessage(value,selected,alt,window.location.origin)})};
 const mutate=async(run:()=>Promise<{ok:boolean;message?:string;version?:number}>,onSuccess?:(result:{ok:boolean;message?:string;version?:number})=>void)=>{setSaving(true);try{const result=await run();if(result.ok)onSuccess?.(result);setNotice(result.ok?"Cambio guardado.":result.message??"No se pudo guardar.");router.refresh()}catch{setNotice("No se pudo guardar. Intenta de nuevo.")}finally{setSaving(false)}};
 const selectedStatus=currentOptimistic?.status??selected?.status; const selectedVersion=currentOptimistic?.version??selected?.version;
 const whatsappHref=selected?customerWhatsAppUrl(selected.phoneE164,activeDraft.message):"#";
 return <main className="mx-auto max-w-7xl p-4 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-primary">Operación diaria</p><h1 className="text-2xl font-bold">Solicitudes</h1><p className="text-sm text-muted-foreground">{page.total} registros · el contador de trabajo considera Nueva, Contactado, Pendiente y estados anteriores abiertos.</p></div><span className="rounded-full bg-secondary px-3 py-2 text-sm font-semibold">{page.items.filter(i=>activeInquiryStatuses.includes(i.status)).length} abiertas en esta página</span></div>
 <form className="mt-5 grid gap-3 rounded-xl border border-border bg-card p-4 sm:grid-cols-2 lg:grid-cols-7"><input name="q" defaultValue={params.q} placeholder="Nombre, teléfono o cabaña" aria-label="Buscar solicitudes" className={`${field} lg:col-span-2`}/><select name="status" defaultValue={params.status??""} aria-label="Filtrar por estado" className={field}><option value="">Todos los estados</option>{businessStatuses.map(s=><option key={s} value={s}>{inquiryStatusLabels[s]}</option>)}</select><select name="cabin" defaultValue={params.cabin??""} aria-label="Filtrar por cabaña" className={field}><option value="">Todas las cabañas</option>{cabins.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" name="from" defaultValue={params.from} aria-label="Desde" className={field}/><input type="date" name="to" defaultValue={params.to} aria-label="Hasta" className={field}/><div className="flex gap-2"><select name="sort" defaultValue={params.sort??"newest"} aria-label="Orden" className={field}><option value="newest">Recientes</option><option value="oldest">Antiguas</option></select><button className={`${button} bg-primary text-primary-foreground`}>Aplicar</button></div></form>
 <div className="mt-5 grid min-w-0 gap-5 lg:grid-cols-[minmax(280px,0.9fr)_minmax(0,1.4fr)]"><section className="space-y-2">{page.items.length===0&&<p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No hay solicitudes con estos filtros.</p>}{page.items.map(item=><Link key={item.id} href={href(params,{selected:item.id,notesPage:undefined,eventsPage:undefined})} className={`block min-h-11 rounded-xl border p-4 hover:bg-muted ${selected?.id===item.id?"border-primary bg-primary/5":"border-border bg-card"}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-semibold">{item.customerName}</p><p className="truncate text-xs text-muted-foreground">{item.phoneDisplay} · {item.cabinName}</p></div><span className="rounded-full bg-secondary px-2 py-1 text-xs font-medium">{inquiryStatusLabels[item.status]}</span></div><p className="mt-2 text-xs">{item.checkIn} → {item.checkOut} · {item.guests} huéspedes</p><p className="mt-1 text-xs text-muted-foreground">Recibida {dateTime(item.createdAt)}</p></Link>)}<nav className="flex items-center justify-between pt-3" aria-label="Paginación"><Link aria-disabled={page.page<=1} href={href(params,{page:Math.max(1,page.page-1),selected:undefined})} className={`${button} ${page.page<=1?"pointer-events-none opacity-40":""}`}><ChevronLeft className="size-4"/>Anterior</Link><span className="text-sm">{page.page} / {page.totalPages}</span><Link aria-disabled={page.page>=page.totalPages} href={href(params,{page:Math.min(page.totalPages,page.page+1),selected:undefined})} className={`${button} ${page.page>=page.totalPages?"pointer-events-none opacity-40":""}`}>Siguiente<ChevronRight className="size-4"/></Link></nav></section>
 {selected&&<section className="min-w-0 rounded-xl border border-border bg-card p-4 sm:p-5"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="text-xl font-bold">{selected.customerName}</h2><a href={`tel:${selected.phoneE164}`} className="text-sm text-primary underline">{selected.phoneDisplay}</a></div><span className="h-fit rounded-full bg-secondary px-3 py-1 text-sm">{inquiryStatusLabels[selectedStatus??selected.status]}</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Solicitud</p><p className="font-medium">{selected.cabinName}</p><p>{selected.checkIn} → {selected.checkOut}</p><p>{selected.guests} huéspedes</p></div><div><p className="text-xs text-muted-foreground">Seguimiento</p><p>Recibida: {dateTime(selected.createdAt)}</p><p>Último contacto: {dateTime(selected.lastContactAt)}</p><p>Actualizada: {dateTime(selected.updatedAt)}</p></div></div><p className="mt-4 rounded-lg bg-secondary/60 p-3 text-sm">{selected.message||"Sin comentarios"}</p>
 <div className="mt-5"><h3 className="font-semibold">Estado de la solicitud</h3><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{businessStatuses.map(status=><button key={status} type="button" disabled={saving||status===selectedStatus} onClick={()=>void mutate(()=>transitionInquiryAction(selected.id,status,selectedVersion??selected.version),(result)=>setOptimistic({id:selected.id,status,version:result.version??selected.version}))} className={button}>{inquiryStatusLabels[status]}</button>)}</div><p className="mt-2 text-xs text-muted-foreground">Abrir WhatsApp no cambia el estado. Marca Contactado sólo después de confirmar el envío.</p>{selectedStatus==="confirmed"&&new Date(`${selected.checkOut}T12:00:00`)<new Date()&&<p className="mt-2 rounded-lg bg-secondary px-3 py-2 text-xs font-medium">Pendiente de cerrar</p>}{selectedStatus==="completed"&&<p className="mt-2 rounded-lg bg-secondary px-3 py-2 text-xs font-medium">Estancia finalizada</p>}</div>
 <div className="mt-6 border-t border-border pt-5"><h3 className="flex items-center gap-2 font-semibold"><MessageCircle className="size-4"/>Enviar WhatsApp</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><select aria-label="Respuesta rápida" value={activeDraft.template} onChange={e=>regenerate(e.target.value as WhatsAppTemplate)} className={field}>{Object.entries(templateLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Cabaña alternativa" value={activeDraft.alternativeId} onChange={e=>{const alt=cabins.find(c=>c.id===e.target.value);regenerate("alternative",alt)}} className={field}><option value="">Ofrecer otra cabaña</option>{cabins.filter(c=>c.id!==selected.cabinId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><textarea aria-label="Mensaje de WhatsApp" value={activeDraft.message} onChange={e=>setDraft({...activeDraft,message:e.target.value})} rows={7} className={`${field} mt-3 h-auto py-3`}/><a href={whatsappHref} target="_blank" rel="noreferrer" onClick={()=>void mutate(()=>recordInquiryContactAction(selected.id,activeDraft.template==="alternative"?"alternative_offered":"whatsapp_opened",alternative?{alternative_cabin_id:alternative.id}:{}))} className={`${button} mt-3 bg-primary text-primary-foreground`}><Send className="size-4"/>Abrir WhatsApp</a></div>
 <div className="mt-6 grid gap-5 border-t border-border pt-5 sm:grid-cols-2"><div><h3 className="flex items-center gap-2 font-semibold"><StickyNote className="size-4"/>Notas internas</h3><textarea aria-label="Nueva nota interna" value={note} onChange={e=>setNote(e.target.value)} rows={3} className={`${field} mt-2 h-auto py-2`}/><button type="button" disabled={saving||!note.trim()} onClick={()=>void mutate(async()=>{const result=await addInquiryNoteAction(selected.id,note);if(result.ok)setNote("");return result})} className={`${button} mt-2`}>Agregar nota</button><ul className="mt-3 space-y-2">{selected.notes.map(n=><li key={n.id} className="rounded-lg bg-secondary/60 p-3 text-sm">{n.body}<span className="mt-1 block text-xs text-muted-foreground">{dateTime(n.createdAt)}</span></li>)}</ul><CrmDetailPagination info={selected.notePage} label="Paginación de notas" field="notesPage" params={params} selected={selected.id}/></div><div><h3 className="flex items-center gap-2 font-semibold"><CalendarDays className="size-4"/>Historial</h3><ol className="mt-3 space-y-3">{selected.events.map(e=><li key={e.id} className="border-l-2 border-primary/30 pl-3 text-sm"><p className="font-medium">{eventLabel[e.type]??e.type}{e.toStatus?`: ${inquiryStatusLabels[e.toStatus]}`:""}</p><p className="text-xs text-muted-foreground">{dateTime(e.createdAt)}</p></li>)}</ol><CrmDetailPagination info={selected.eventPage} label="Paginación de historial" field="eventsPage" params={params} selected={selected.id}/></div></div><Link href={`/panel/clientes?selected=${selected.customerId}`} className={`${button} mt-5`}><Users className="size-4"/>Ver perfil del cliente</Link>{notice&&<p role="status" className="mt-3 text-sm font-medium text-primary">{notice}</p>}</section>}</div></main> }
